# Generated by Django 4.1 on 2025-04-06 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('lastname', models.CharField(max_length=100, verbose_name='Apellido')),
                ('address', models.CharField(max_length=255, verbose_name='Dirección')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('neighborhood', models.TextField(max_length=100, verbose_name='Vecindario')),
                ('cedula', models.CharField(max_length=20, verbose_name='Cédula')),
                ('phone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=100, verbose_name='Correo electrónico')),
                ('income', models.DecimalField(decimal_places=2, max_digits=60, verbose_name='Ingresos')),
                ('source_of_income', models.TextField(max_length=100, verbose_name='Ocupacion del Cliente')),
                ('employment_situation', models.TextField(max_length=100, verbose_name='Situacion laboral del Cliente')),
                ('producto_solicitados', models.TextField(max_length=100, verbose_name='Producto solicitado')),
                ('record_date', models.DateField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='pdfs/')),
            ],
        ),
    ]
