# Generated by Django 4.1 on 2025-04-11 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='employment_situation',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Situacion laboral del Cliente'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=60, null=True, verbose_name='Ingresos'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='producto_solicitados',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Producto solicitado'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='source_of_income',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Ocupacion del Cliente'),
        ),
    ]
